### PR TITLE
Added support for DHO800 series oscilloscopes and basic individual channel scaling/gain setting

### PR DESCRIPTION
**Pull request by yspacedev**
image
image

- Support for parsing bin files from Rigol DHO800 series scopes. They use a slightly different header structure, so you need to use the flag --DHO800 for the binaries to be processed correctly
- Basic individual channel scaling/gain adjustment. Select channel and input the factor you want to scale values on that channel by.
- Optional thing: trace colors match the yellow, blue, magenta, green color scheme of Tektronix scopes (since it seems to be the most commonly used color scheme)

### CODE REVIEW

**Comment by yspacedev** [comment]
[DHO804test.zip](https://github.com/sam210723/wavebin/files/14133075/DHO804test.zip)
Here's a test file

**Comment by sam210723** [comment]
Thanks for the PR! I'll test it out and hopefully find a way to auto-detect the extra bytes in the DHO header.

**Comment by yspacedev** [comment]
Maybe the version in the header is different for the DHO and other Rigol scopes (It seems to be 3 on the DHO and 1 on the MXO). Maybe you could also detect the longer header since there are 4 extra bytes (all 0 from my testing) before the channel number.

**Comment by sam210723** [comment]
I found info on the different header format, all they've done is change the file size field from 4 bytes to 8 bytes. I'll use the file version field to detect this and use a different struct string to unpack the header.

**Comment by sam210723** [comment]
Merging into another branch to make a few changes

**Comment by sam210723** [comment]
Detecting the header type by file format version is all working, will merge to master now

**Pull request merged**
